import { StyleSheet } from "react-native";

export default StyleSheet.create({
  arrowImage: {
    width: 6,
    height: 12,
  },
  arrowImage2: {
    width: 6,
    height: 12,
    marginBottom: 21,
    marginRight: 10,
  },
  arrowImage3: {
    width: 6,
    height: 12,
    marginRight: 20,
    marginBottom: 20,
  },
  arrowImage4: {
    width: 6,
    height: 12,
    marginBottom: 20,
  },
  container: {
    flex: 1,
    backgroundColor: "black",
  },
  list: {
    flex: 1,
  },
  line: {
    height: 100,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#303030",
    borderBottomStyle: "solid",
  },
  lineMain: {
    height: 70,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginLeft: 33,
    marginTop: 57,
  },
  lineMain1: {
    height: 100,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 30,
  },
  lineMainStatistics: {
    height: 70,
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    marginLeft: 33,
    marginBottom: 10,
  },
  lineText: {
    fontSize: 15,
    height: 22,
    color: "rgba(255, 255, 255, 0.5)",
  },
  text: {
    color: "white",
    fontSize: 15,
    fontStyle: "normal",
    height: 22,
  },
  containerFistPage: {
    flex: 1,
    backgroundColor: "black",
    alignItems: "center",
    justifyContent: "center",
  },
  footerContainer: {
    position: "absolute",
    bottom: 0,
    width: "100%",
  },
  imageStatistics: {
    width: 210,
    height: 22,
    resizeMode: "contain",
    marginBottom: 23,
  },
  imageSOE: {
    width: 204,
    height: 44,
    resizeMode: "contain",
    marginBottom: 23,
  },
  imageShop: {
    width: 148,
    height: 22,
    resizeMode: "contain",
    marginBottom: 23,
  },
  imageSI: {
    width: 256,
    height: 22,
    resizeMode: "contain",
    marginBottom: 23,
  },
  imageIN16: {
    width: 148,
    height: 22,
    resizeMode: "contain",
    marginBottom: 24,
    marginTop: 40,
  },
  imageExtras: {
    width: 148,
    height: 22,
    resizeMode: "contain",
    marginBottom: 23,
  },
  logo: {
    width: 161,
    height: 165,
  },

  imageLoading: {
    position: "absolute",
    bottom: 51,
    width: 122.86,
    height: 13,
  },
  orangeText: {
    color: "#FFA800",
    fontWeight: 900,
  },
  imageBattery: {
    width: 166,
    height: 22,
    resizeMode: "contain",
    marginBottom: 24,
    marginTop: 40,
  },
  mapCharging: {
    marginTop: 14,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  textCharging: {
    borderRadius: 4,
    width: 82,
    overflow: "hidden",
    backgroundColor: "#66C770",
    textAlign: "center",
  },
  image12: {
    width: 323,
    height: 321,
    resizeMode: "contain",
    marginBottom: 24,
    marginLeft: 30,
  },
  center: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  textConnected: {
    borderRadius: 4,
    width: 82,
    overflow: "hidden",
    backgroundColor: "#66C770",
    textAlign: "center",
  },
  rowBattery: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },

  imageIducation: {
    width: 207,
    height: 22,
    resizeMode: "contain",
    marginLeft: 20,
    marginBottom: 24,
    marginTop: 40,
  },

  lineMain2: {
    height: 100,
    flexDirection: "row",
    alignItems: "center",
    padding: 22,
  },
  battery: {
    width: 76,
    height: 287,
    resizeMode: "contain",
    marginBottom: 24,
    marginTop: 40,
  },
  cellPoint: {
    marginRight: 4,
    width: 10,
    height: 50,
    backgroundColor: "#FFA800",
    borderRadius: 50,
  },
  cellPointOff: {
    marginRight: 4,
    width: 10,
    height: 50,
    backgroundColor: "#4A4A4A",
    borderRadius: 50,
  },
  imageDATA: {
    width: 216,
    height: 22,
    resizeMode: "contain",
    marginBottom: 23,
  },
  viewButton: {
    flex: 1,
    marginLeft: 17,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    bottom: 20,
    left: 0,
    right: 0,
  },
  styleButton: {
    padding: 10,
    width: 339,
    height: 50,
    backgroundColor: "white",
    position: "absolute",
    bottom: 60, // установить высоту, равную высоте Footer + отступ от него
    justifyContent: "center",
    alignItems: "center", // добавлено свойство
  },
  viewFooter: {
    position: "fixed",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    height: 70,
  },
  hammer: {
    width: 20,
    height: 22,
    resizeMode: "contain",
    marginBottom: 24,
    marginTop: 40,
  },
  imageIconFooter2: {
    width: 20,
    height: 22,
    resizeMode: "contain",
    marginBottom: 24,
    marginTop: 40,
    marginLeft: 20,
  },
  search: {
    width: 70,
    height: 72,
    resizeMode: "contain",
    marginBottom: 24,
    marginTop: 40,
  },
  user: {
    width: 20,
    height: 22,
    resizeMode: "contain",
    marginBottom: 24,
    marginTop: 40,
  },
  imageIcon: {
    width: 20,
    height: 22,
    resizeMode: "contain",
    marginBottom: 24,
    marginTop: 40,
  },
  imageIconFooter2: {
    width: 20,
    height: 22,
    resizeMode: "contain",
    marginBottom: 24,
    marginTop: 40,
  },
  shoppingCart: {
    width: 20,
    height: 22,
    resizeMode: "contain",
    marginBottom: 24,
    marginTop: 40,
  },
  imageStar: {
    width: 20,
    height: 22,
    resizeMode: "contain",
    marginBottom: 24,
    marginTop: 40,
  },
  imageSetting: {
    width: 181,
    height: 22,
    resizeMode: "contain",
    marginBottom: 60,
  },
});
